spring:
  application:
    name: challange
  datasource:
    url: jdbc:mysql://localhost:3306/challange
    username: root
    password: 8718
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    locations: classpath:db/migration
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
jwt:
   private:
     key: classpath:app.key
   public:
     key: classpath:app.pub


