spring:
  cache:
    type: redis
  application:
    name: desafio
  datasource:
    url: jdbc:mysql://127.0.0.1:3309/desafio
    username: root
    password: 8718
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 2006

